### ISSUE TITLE
Undefined `c_w` in update step

### ISSUE THREAD

**Issue by etpinard** [gl-vis/gl-contour2d#1]
Variable [`c_w`](https://github.com/gl-vis/gl-contour2d/blob/master/contour.js#L195) is undefined in the update step. More precisely, in the loop over the weights.

Hard-coding `c_w = 1`, and using [`example/simple.js`](https://github.com/gl-vis/gl-contour2d/blob/master/example/simple.js) gives:

![image](https://cloud.githubusercontent.com/assets/6675409/11823242/ff99e5ce-a340-11e5-8acf-cbf9bc830972.png)

**Comment by mikolalysenko** [comment]
Ah, I didn't finish this up before I left.  I made a quick push that should solve it.  Picking still doesn't work though.

**Comment by etpinard** [comment]
@mikolalysenko thanks!
